### ISSUE TITLE
search an Expert

### ISSUE THREAD

**Issue by jk0ehn** [jk0ehn/capstone-project#1]
As a user 
I want to find a guide
who help me with medical cannabis
so that I can talk to an expert

//*image

## ac

- [x]  promise
- [x] logo
- [x]  theres a searchinputfield on the screen
- [x] searchinputfield includes placeholder (city or zip code)

## tasks

- [x] create index
- [x] create h1
- [x] create searchinputfield
- [x] position the searchinputfield
- [x] add button

![Image](https://user-images.githubusercontent.com/109575621/191239675-ec62a3e5-11d5-42ac-8111-89117b74942f.png)

**Comment by AnH13-6** [comment]
For the user story I would always just write about the current step. Here it might be something like: "as a user I want to have a search bar on a page so that I can search for cities."
Is the Logo a placeholder? Maybe delete it for now as we shouldn't have things without function or meaning I think. 
Spelling: "Where do you want to look?" ((delete "for"))
"Enter City ..." ((not citiy))

Sorry for the long text 🙈 But otherwise it's a nice short and clear user story!
