### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by jk0ehn** [jk0ehn/capstone-project#11]
As a user
I want to write a message
to get in touch with an expert

![Image](https://user-images.githubusercontent.com/109575621/195364756-70d7982a-bfe4-4471-bba2-eb97a2771ed4.png)

## ac

- [ ]  ability to leave a message

## tasks

- [ ] create inputfields for name, phone,mail and message
- [ ] add send-button
