### ISSUE TITLE
list experts

### ISSUE THREAD

**Issue by jk0ehn** [jk0ehn/capstone-project#4]

**Comment by jk0ehn** [comment]
As a user 
I want to search an expert
who help me with medical cannabis
so that I can talk to an expert directly

![Image](https://user-images.githubusercontent.com/109575621/192249772-efd2d765-2990-4a93-b3c9-0c11412c2dd5.png)


## ac

- [ ]  searchbar
- [ ] show expert cards with detailed informations



## tasks
 
- [ ] create searchbar
- [ ] create json for detailed informations
- [ ] create function to list informations in card
- [ ] list card
- [ ] create function to filter city information to display on screen

**Comment by mbosselmann** [comment]
Hi Julian,

I like your user story! Just three remarks:
- As far as I know the wireframe, which I like very much, is usually packed between the value proposition and the acceptance criteria under the title description. Do you want to change this or is there something against this structure?
- Your value proposition seems to miss one word.
As a user
I want **to** search an expert
who can help me with medical cannabis
so that I can talk directly to an expert
- And I would highly recommend you to implement the backend as a next or another step as this is a huge task. Usually you would write a separate user story for implementing the backend and if I did understand your user story correctly you also want to build some frontend components to fulfill this user story.

If you have questions, feel free to ask me. :)

**Comment by jk0ehn** [comment]
Hey Mareike, thanks for your feedback!

Oh ok, I don't know about the order. So yes, I changed it.

For list an expert card I need some data, so what should I do first in your opinion? Is this the backend for a user story?
