### ISSUE TITLE
expert details

### ISSUE THREAD

**Issue by jk0ehn** [jk0ehn/capstone-project#6]
As a user
I want to get in touch with the choosen local expert
so that I can make an appointment

![Image](https://user-images.githubusercontent.com/109575621/192468508-4a2292fb-1f87-4726-be81-72044c94081b.png)

## ac

- [ ]  expert image
- [ ] show detailed information
- [ ] home-button (or GoBack - button) 
- [ ] message-button
- [ ] appointment-button

## tasks
 
- [ ] use Image
- [ ] fetch detailed datas
- [ ] list detailed informations
- [ ] create buttons
- [ ] link buttons

**Comment by Murci2022** [comment]
Great job Julian, looks good to me!
